spring.application.name=hitbox-usuario-api
server.port=8081
server.address=0.0.0.0
server.servlet.context-path=/api/usuario/hitbox

# JPA Spring configurations
spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=hitbox}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha01}
spring.datasource.driver-class-name=org.postgresql.Driver

secret.key.api=a9f4c2e8b7d14f6c93a1e5b8c7d2f09e4a6c1b3f8d2e7a9c5b4e1f6d8c3a2b7